# Generated by Django 3.0.2 on 2021-05-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_auto_20210425_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
