# Generated by Django 3.0.2 on 2021-05-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_auto_20210503_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('prod_name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('picture', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
