# Generated by Django 3.0.2 on 2021-05-03 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0007_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_name',
            new_name='product_name',
        ),
    ]
