# Generated by Django 3.0.2 on 2021-05-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0010_auto_20210510_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='enter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
