# Generated by Django 3.0.2 on 2021-05-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0011_auto_20210510_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
