# Generated by Django 3.0.2 on 2021-05-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0013_auto_20210518_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apt_num',
            field=models.IntegerField(verbose_name='מספר דירה'),
        ),
        migrations.AlterField(
            model_name='address',
            name='enter',
            field=models.IntegerField(blank=True, null=True, verbose_name='קוד כניסה'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_num',
            field=models.IntegerField(verbose_name='מספר בית'),
        ),
        migrations.AlterField(
            model_name='address',
            name='level',
            field=models.IntegerField(verbose_name='קומה'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=5, verbose_name='רחוב'),
        ),
        migrations.AlterField(
            model_name='address',
            name='town',
            field=models.CharField(max_length=30, verbose_name='עיר'),
        ),
    ]
