# Generated by Django 3.0.2 on 2021-05-18 22:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitations', '0015_buy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buy',
            new_name='ProdUser',
        ),
    ]
