# Generated by Django 3.0.2 on 2021-05-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0016_auto_20210519_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produser',
            name='until_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
