# Generated by Django 3.0.2 on 2021-05-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0017_auto_20210519_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produser',
            name='day',
            field=models.IntegerField(choices=[(6, 'SUNDAY'), (0, 'MONDAY'), (1, 'TUESDAY'), (2, 'WEDNESDAY'), (3, 'THURSDAY'), (4, 'FRIDAY')], default=3),
        ),
    ]
