# Generated by Django 3.0.2 on 2021-05-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0018_auto_20210519_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
