# Generated by Django 3.0.2 on 2021-05-18 22:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0019_auto_20210519_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(default=datetime.datetime(2021, 5, 18, 22, 34, 20, 838245, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
