# Generated by Django 3.0.2 on 2021-05-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0020_contact_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('לחמניות', 'לחמניות'), ('מוצרי חלב', 'מוצרי חלב'), ('מיצים', 'מיצים'), ('מאפים', 'מאפים')], max_length=30),
        ),
    ]
