# Generated by Django 3.0.2 on 2021-05-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0021_auto_20210519_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('לחמניות', 'Lh'), ('מוצרי חלב', 'Hl'), ('מיצים', 'Mz'), ('מאפים', 'Ma')], max_length=20),
        ),
    ]
