# Generated by Django 3.0.2 on 2021-05-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0023_auto_20210520_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
    ]
