# Generated by Django 3.0.2 on 2021-07-07 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitations', '0025_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=50, verbose_name='רחוב'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LH', 'לחמניות'), ('HL', 'מוצרי חלב'), ('MZ', 'מיצים'), ('MA', 'מאפים')], max_length=20),
        ),
        migrations.AlterField(
            model_name='produser',
            name='day',
            field=models.IntegerField(choices=[(6, 'יום ראשון'), (0, 'יום שני'), (1, 'יום שלישי'), (2, 'יום רביעי'), (3, 'יום חמישי'), (4, 'יום שישי')]),
        ),
    ]
