# Generated by Django 3.0.2 on 2021-07-08 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitations', '0027_auto_20210708_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produser',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='produser',
            name='until_date',
        ),
        migrations.AlterField(
            model_name='produser',
            name='day',
            field=models.IntegerField(choices=[(0, 'יום ראשון'), (1, 'יום שני'), (2, 'יום שלישי'), (3, 'יום רביעי'), (4, 'יום חמישי'), (5, 'יום שישי')]),
        ),
        migrations.CreateModel(
            name='BuyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitations.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
