# Generated by Django 3.0.2 on 2021-08-08 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0028_auto_20210708_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produser',
            name='is_active',
        ),
    ]
